name: @pluginName@
author: @author@
website: @website@
version: @project.version@
main: @mainClass@
api-version: 1.13
softdepend: [Vault, Citizens, PlaceholderAPI, ProtocolLib, mcMMO, WorldGuard, RedProtect]
commands:
  morefish:
    description: Main command for MoreFish.
    usage: /morefish
    aliases: [mf, fish]
permissions:
  morefish.admin:
    default: op
    description: Give user ability to control the fishing contest.
  morefish.help:
    default: true
    description: Player with this permission can use the help command.
  morefish.top:
    default: true
    description: Player with this permission can use /morefish top command.
  morefish.shop:
    default: op
    description: Player with this permission can use /morefish shop command.